# Generated by Django 5.1.4 on 2025-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('wash', 'lavagem simples'), ('polish', 'polimento'), ('wax', 'encerramento')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
